# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ARITHMETIC_RIGHT_SHIFT_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ARITHMETIC_RIGHT_SHIFT_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsARITHMETIC_RIGHT_SHIFT_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ARITHMETIC_RIGHT_SHIFT_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # ARITHMETIC_RIGHT_SHIFT_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ARITHMETIC_RIGHT_SHIFT_Attribute
    def Round(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ARITHMETIC_RIGHT_SHIFT_AttributeStart(builder):
    builder.StartObject(1)

def Start(builder):
    ARITHMETIC_RIGHT_SHIFT_AttributeStart(builder)

def ARITHMETIC_RIGHT_SHIFT_AttributeAddRound(builder, round):
    builder.PrependBoolSlot(0, round, 0)

def AddRound(builder, round):
    ARITHMETIC_RIGHT_SHIFT_AttributeAddRound(builder, round)

def ARITHMETIC_RIGHT_SHIFT_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ARITHMETIC_RIGHT_SHIFT_AttributeEnd(builder)
