# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

class Attribute(object):
    NONE = 0
    PoolAttribute = 1
    ConvAttribute = 2
    TransposeConvAttribute = 3
    PadAttribute = 4
    AxisAttribute = 5
    ResizeAttribute = 6
    ClampAttribute = 7
    RescaleAttribute = 8
    MulAttribute = 9
    ArithmeticRightShiftAttribute = 10
    CondIfAttribute = 11
    WhileLoopAttribute = 12
    TransposeAttribute = 13
    TableAttribute = 14
    MatMulAttribute = 15
    FullyConnectedAttribute = 16
    NegateAttribute = 17
    CustomAttribute = 18
    FFTAttribute = 19
    RFFTAttribute = 20
