# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConcatAttribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConcatAttribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConcatAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ConcatAttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # ConcatAttribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConcatAttribute
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ConcatAttributeStart(builder):
    builder.StartObject(1)

def Start(builder):
    ConcatAttributeStart(builder)

def ConcatAttributeAddAxis(builder, axis):
    builder.PrependInt32Slot(0, axis, 0)

def AddAxis(builder, axis):
    ConcatAttributeAddAxis(builder, axis)

def ConcatAttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConcatAttributeEnd(builder)
