# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class COND_IF_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = COND_IF_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCOND_IF_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def COND_IF_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # COND_IF_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # COND_IF_Attribute
    def ThenGraph(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # COND_IF_Attribute
    def ElseGraph(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def COND_IF_AttributeStart(builder):
    builder.StartObject(2)

def Start(builder):
    COND_IF_AttributeStart(builder)

def COND_IF_AttributeAddThenGraph(builder, thenGraph):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(thenGraph), 0)

def AddThenGraph(builder, thenGraph):
    COND_IF_AttributeAddThenGraph(builder, thenGraph)

def COND_IF_AttributeAddElseGraph(builder, elseGraph):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(elseGraph), 0)

def AddElseGraph(builder, elseGraph):
    COND_IF_AttributeAddElseGraph(builder, elseGraph)

def COND_IF_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return COND_IF_AttributeEnd(builder)
