# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CUSTOM_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CUSTOM_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCUSTOM_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CUSTOM_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # CUSTOM_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CUSTOM_Attribute
    def OperatorName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CUSTOM_Attribute
    def DomainName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CUSTOM_Attribute
    def ImplementationAttrs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # CUSTOM_Attribute
    def ImplementationAttrsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # CUSTOM_Attribute
    def ImplementationAttrsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CUSTOM_Attribute
    def ImplementationAttrsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def CUSTOM_AttributeStart(builder):
    builder.StartObject(3)

def Start(builder):
    CUSTOM_AttributeStart(builder)

def CUSTOM_AttributeAddOperatorName(builder, operatorName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(operatorName), 0)

def AddOperatorName(builder, operatorName):
    CUSTOM_AttributeAddOperatorName(builder, operatorName)

def CUSTOM_AttributeAddDomainName(builder, domainName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(domainName), 0)

def AddDomainName(builder, domainName):
    CUSTOM_AttributeAddDomainName(builder, domainName)

def CUSTOM_AttributeAddImplementationAttrs(builder, implementationAttrs):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(implementationAttrs), 0)

def AddImplementationAttrs(builder, implementationAttrs):
    CUSTOM_AttributeAddImplementationAttrs(builder, implementationAttrs)

def CUSTOM_AttributeStartImplementationAttrsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartImplementationAttrsVector(builder, numElems):
    return CUSTOM_AttributeStartImplementationAttrsVector(builder, numElems)

def CUSTOM_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return CUSTOM_AttributeEnd(builder)
