# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FFT2D_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FFT2D_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFFT2D_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FFT2D_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # FFT2D_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FFT2D_Attribute
    def Inverse(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FFT2D_Attribute
    def LocalBound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def FFT2D_AttributeStart(builder):
    builder.StartObject(2)

def Start(builder):
    FFT2D_AttributeStart(builder)

def FFT2D_AttributeAddInverse(builder, inverse):
    builder.PrependBoolSlot(0, inverse, 0)

def AddInverse(builder, inverse):
    FFT2D_AttributeAddInverse(builder, inverse)

def FFT2D_AttributeAddLocalBound(builder, localBound):
    builder.PrependBoolSlot(1, localBound, 0)

def AddLocalBound(builder, localBound):
    FFT2D_AttributeAddLocalBound(builder, localBound)

def FFT2D_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return FFT2D_AttributeEnd(builder)
