# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LOGICAL_XOR_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LOGICAL_XOR_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLOGICAL_XOR_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LOGICAL_XOR_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # LOGICAL_XOR_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def LOGICAL_XOR_AttributeStart(builder):
    builder.StartObject(0)

def Start(builder):
    LOGICAL_XOR_AttributeStart(builder)

def LOGICAL_XOR_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return LOGICAL_XOR_AttributeEnd(builder)
