# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MATMUL_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MATMUL_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMATMUL_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MATMUL_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # MATMUL_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MATMUL_Attribute
    def AZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MATMUL_Attribute
    def BZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MATMUL_AttributeStart(builder):
    builder.StartObject(2)

def Start(builder):
    MATMUL_AttributeStart(builder)

def MATMUL_AttributeAddAZp(builder, aZp):
    builder.PrependInt32Slot(0, aZp, 0)

def AddAZp(builder, aZp):
    MATMUL_AttributeAddAZp(builder, aZp)

def MATMUL_AttributeAddBZp(builder, bZp):
    builder.PrependInt32Slot(1, bZp, 0)

def AddBZp(builder, bZp):
    MATMUL_AttributeAddBZp(builder, bZp)

def MATMUL_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return MATMUL_AttributeEnd(builder)
