# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MinimumAttribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MinimumAttribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMinimumAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MinimumAttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # MinimumAttribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MinimumAttribute
    def NanMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def MinimumAttributeStart(builder):
    builder.StartObject(1)

def Start(builder):
    MinimumAttributeStart(builder)

def MinimumAttributeAddNanMode(builder, nanMode):
    builder.PrependUint32Slot(0, nanMode, 0)

def AddNanMode(builder, nanMode):
    MinimumAttributeAddNanMode(builder, nanMode)

def MinimumAttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return MinimumAttributeEnd(builder)
