# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NEGATE_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NEGATE_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNEGATE_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NEGATE_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # NEGATE_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NEGATE_Attribute
    def Input1Zp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # NEGATE_Attribute
    def OutputZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def NEGATE_AttributeStart(builder):
    builder.StartObject(2)

def Start(builder):
    NEGATE_AttributeStart(builder)

def NEGATE_AttributeAddInput1Zp(builder, input1Zp):
    builder.PrependInt32Slot(0, input1Zp, 0)

def AddInput1Zp(builder, input1Zp):
    NEGATE_AttributeAddInput1Zp(builder, input1Zp)

def NEGATE_AttributeAddOutputZp(builder, outputZp):
    builder.PrependInt32Slot(1, outputZp, 0)

def AddOutputZp(builder, outputZp):
    NEGATE_AttributeAddOutputZp(builder, outputZp)

def NEGATE_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return NEGATE_AttributeEnd(builder)
