# automatically generated by the FlatBuffers compiler, do not modify

# Copyright (c) 2020-2021, ARM Limited.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.


# namespace: tosa

class Op(object):
    UNKNOWN = 0
    ARGMAX = 1
    AVG_POOL2D = 2
    CONV2D = 3
    CONV3D = 4
    DEPTHWISE_CONV2D = 5
    FULLY_CONNECTED = 6
    MATMUL = 7
    MAX_POOL2D = 8
    TRANSPOSE_CONV2D = 9
    CLAMP = 10
    RELUN = 11
    SIGMOID = 12
    TANH = 13
    ADD = 14
    ARITHMETIC_RIGHT_SHIFT = 15
    BITWISE_AND = 16
    BITWISE_OR = 17
    BITWISE_XOR = 18
    LOGICAL_AND = 19
    LOGICAL_LEFT_SHIFT = 20
    LOGICAL_RIGHT_SHIFT = 21
    LOGICAL_OR = 22
    LOGICAL_XOR = 23
    MAXIMUM = 24
    MINIMUM = 25
    MUL = 26
    POW = 27
    SUB = 28
    TABLE = 29
    ABS = 30
    BITWISE_NOT = 31
    CEIL = 32
    CLZ = 33
    EXP = 34
    FLOOR = 35
    LOG = 36
    LOGICAL_NOT = 37
    NEGATE = 38
    RECIPROCAL = 39
    RSQRT = 40
    SELECT = 41
    EQUAL = 42
    GREATER = 43
    GREATER_EQUAL = 44
    REDUCE_ANY = 45
    REDUCE_ALL = 46
    REDUCE_MAX = 47
    REDUCE_MIN = 48
    REDUCE_PRODUCT = 49
    REDUCE_SUM = 50
    CONCAT = 51
    PAD = 52
    RESHAPE = 53
    REVERSE = 54
    SLICE = 55
    TILE = 56
    TRANSPOSE = 57
    GATHER = 58
    SCATTER = 59
    RESIZE = 60
    CAST = 61
    RESCALE = 62
    CONST = 63
    PLACEHOLDER = 64
    IDENTITY = 65
    IDENTITYN = 66
    CUSTOM = 67
    COND_IF = 68
    WHILE_LOOP = 69

