# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RandUniformAttribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RandUniformAttribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRandUniformAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RandUniformAttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # RandUniformAttribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RandUniformAttribute
    def UseSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def RandUniformAttributeStart(builder):
    builder.StartObject(1)

def Start(builder):
    RandUniformAttributeStart(builder)

def RandUniformAttributeAddUseSeed(builder, useSeed):
    builder.PrependBoolSlot(0, useSeed, 0)

def AddUseSeed(builder, useSeed):
    RandUniformAttributeAddUseSeed(builder, useSeed)

def RandUniformAttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RandUniformAttributeEnd(builder)
