# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReduceMinAttribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReduceMinAttribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReduceMinAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ReduceMinAttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # ReduceMinAttribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReduceMinAttribute
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ReduceMinAttribute
    def NanMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ReduceMinAttributeStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReduceMinAttributeStart(builder)

def ReduceMinAttributeAddAxis(builder, axis):
    builder.PrependInt32Slot(0, axis, 0)

def AddAxis(builder, axis):
    ReduceMinAttributeAddAxis(builder, axis)

def ReduceMinAttributeAddNanMode(builder, nanMode):
    builder.PrependUint32Slot(1, nanMode, 0)

def AddNanMode(builder, nanMode):
    ReduceMinAttributeAddNanMode(builder, nanMode)

def ReduceMinAttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReduceMinAttributeEnd(builder)
