# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RESIZE_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RESIZE_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRESIZE_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RESIZE_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # RESIZE_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RESIZE_Attribute
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def RESIZE_AttributeStart(builder):
    builder.StartObject(1)

def Start(builder):
    RESIZE_AttributeStart(builder)

def RESIZE_AttributeAddMode(builder, mode):
    builder.PrependUint32Slot(0, mode, 0)

def AddMode(builder, mode):
    RESIZE_AttributeAddMode(builder, mode)

def RESIZE_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RESIZE_AttributeEnd(builder)
