# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RFFT2dAttribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RFFT2dAttribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRFFT2dAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RFFT2dAttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # RFFT2dAttribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RFFT2dAttribute
    def LocalBound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def RFFT2dAttributeStart(builder):
    builder.StartObject(1)

def Start(builder):
    RFFT2dAttributeStart(builder)

def RFFT2dAttributeAddLocalBound(builder, localBound):
    builder.PrependBoolSlot(0, localBound, 0)

def AddLocalBound(builder, localBound):
    RFFT2dAttributeAddLocalBound(builder, localBound)

def RFFT2dAttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RFFT2dAttributeEnd(builder)
