# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SortAttribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SortAttribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSortAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SortAttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # SortAttribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SortAttribute
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SortAttribute
    def Descending(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SortAttributeStart(builder): builder.StartObject(2)
def Start(builder):
    return SortAttributeStart(builder)
def SortAttributeAddAxis(builder, axis): builder.PrependInt32Slot(0, axis, 0)
def AddAxis(builder, axis):
    return SortAttributeAddAxis(builder, axis)
def SortAttributeAddDescending(builder, descending): builder.PrependBoolSlot(1, descending, 0)
def AddDescending(builder, descending):
    return SortAttributeAddDescending(builder, descending)
def SortAttributeEnd(builder): return builder.EndObject()
def End(builder):
    return SortAttributeEnd(builder)