# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TRANSPOSE_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TRANSPOSE_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTRANSPOSE_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TRANSPOSE_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # TRANSPOSE_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TRANSPOSE_Attribute
    def Perms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TRANSPOSE_Attribute
    def PermsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # TRANSPOSE_Attribute
    def PermsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TRANSPOSE_Attribute
    def PermsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TRANSPOSE_AttributeStart(builder):
    builder.StartObject(1)

def Start(builder):
    TRANSPOSE_AttributeStart(builder)

def TRANSPOSE_AttributeAddPerms(builder, perms):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(perms), 0)

def AddPerms(builder, perms):
    TRANSPOSE_AttributeAddPerms(builder, perms)

def TRANSPOSE_AttributeStartPermsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPermsVector(builder, numElems):
    return TRANSPOSE_AttributeStartPermsVector(builder, numElems)

def TRANSPOSE_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return TRANSPOSE_AttributeEnd(builder)
