# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TRANSPOSE_CONV2D_Attribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TRANSPOSE_CONV2D_Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTRANSPOSE_CONV2D_Attribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TRANSPOSE_CONV2D_AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # TRANSPOSE_CONV2D_Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TRANSPOSE_CONV2D_Attribute
    def OutPad(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TRANSPOSE_CONV2D_Attribute
    def OutPadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # TRANSPOSE_CONV2D_Attribute
    def OutPadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TRANSPOSE_CONV2D_Attribute
    def OutPadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # TRANSPOSE_CONV2D_Attribute
    def Stride(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TRANSPOSE_CONV2D_Attribute
    def StrideAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # TRANSPOSE_CONV2D_Attribute
    def StrideLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TRANSPOSE_CONV2D_Attribute
    def StrideIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # TRANSPOSE_CONV2D_Attribute
    def InputZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TRANSPOSE_CONV2D_Attribute
    def WeightZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TRANSPOSE_CONV2D_Attribute
    def LocalBound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TRANSPOSE_CONV2D_Attribute
    def AccType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def TRANSPOSE_CONV2D_AttributeStart(builder):
    builder.StartObject(6)

def Start(builder):
    TRANSPOSE_CONV2D_AttributeStart(builder)

def TRANSPOSE_CONV2D_AttributeAddOutPad(builder, outPad):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(outPad), 0)

def AddOutPad(builder, outPad):
    TRANSPOSE_CONV2D_AttributeAddOutPad(builder, outPad)

def TRANSPOSE_CONV2D_AttributeStartOutPadVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutPadVector(builder, numElems):
    return TRANSPOSE_CONV2D_AttributeStartOutPadVector(builder, numElems)

def TRANSPOSE_CONV2D_AttributeAddStride(builder, stride):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(stride), 0)

def AddStride(builder, stride):
    TRANSPOSE_CONV2D_AttributeAddStride(builder, stride)

def TRANSPOSE_CONV2D_AttributeStartStrideVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStrideVector(builder, numElems):
    return TRANSPOSE_CONV2D_AttributeStartStrideVector(builder, numElems)

def TRANSPOSE_CONV2D_AttributeAddInputZp(builder, inputZp):
    builder.PrependInt32Slot(2, inputZp, 0)

def AddInputZp(builder, inputZp):
    TRANSPOSE_CONV2D_AttributeAddInputZp(builder, inputZp)

def TRANSPOSE_CONV2D_AttributeAddWeightZp(builder, weightZp):
    builder.PrependInt32Slot(3, weightZp, 0)

def AddWeightZp(builder, weightZp):
    TRANSPOSE_CONV2D_AttributeAddWeightZp(builder, weightZp)

def TRANSPOSE_CONV2D_AttributeAddLocalBound(builder, localBound):
    builder.PrependBoolSlot(4, localBound, 0)

def AddLocalBound(builder, localBound):
    TRANSPOSE_CONV2D_AttributeAddLocalBound(builder, localBound)

def TRANSPOSE_CONV2D_AttributeAddAccType(builder, accType):
    builder.PrependUint32Slot(5, accType, 0)

def AddAccType(builder, accType):
    TRANSPOSE_CONV2D_AttributeAddAccType(builder, accType)

def TRANSPOSE_CONV2D_AttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return TRANSPOSE_CONV2D_AttributeEnd(builder)
